#raghudevops25/studentapp:v2
FROM tomcat:9 
ADD https://github.com/cit-latex/stack/raw/master/student.war /usr/local/tomcat/webapps/student.war 
ADD context.xml /usr/local/tomcat/conf/context.xml 
ADD https://github.com/cit-latex/stack/raw/master/mysql-connector-java-5.1.40.jar /usr/local/tomcat/lib/mysql-connector-java-5.1.40.jar
